### ISSUE TITLE
How to change font type and size

### ISSUE THREAD

**Issue by DanielIAvila** [praseodym/tudelft-report-latex#5]
Hi, 

I have been working with the template in Overleaf. However, after reading all the documentation I cannot find where can I change the font that is used all over the document and its size.

Any comments?

**Comment by praseodym** [comment]
It's a template for a reason: you're not supposed to change the fonts.

However, if you still want to do so, they're defined in tudelft-report.cls:
https://github.com/praseodym/tudelft-report-latex/blob/f38aa26ce9d09953a50ce7b91bb199d83c56223c/tudelft-report.cls#L80-L106
