### ISSUE TITLE
German as default language?

### ISSUE THREAD

**Issue by Ademord** [praseodym/tudelft-report-latex#6]
Hello, on your documentation you say the default language is english but when I use your template the default language is german, and when I set [german] as the document class parameter it goes to english. Did you by mistake mix these two or is something in my local settings off?

**Comment by praseodym** [comment]
There is no setting for German, so I'm not sure what is happening. English is default, and Dutch is [supported with the `[dutch]` document class parameter](https://github.com/praseodym/tudelft-report-latex/blob/f38aa26ce9d09953a50ce7b91bb199d83c56223c/tudelft-report.cls#L30-L48).
